language: node_js
node_js:
  - '5'
  - '4'
deploy:
  skip_cleanup: true
  provider: script
  script: ./scripts/deploy.sh
  'on':
    branch: master
    node: '5'
env:
  global:
    - secure: >-
        UZC/ZALRNDS7ddND54/L0/HDTSyXya5XL0JfbAQNCPt+vwPcfZ7sdzpYljR4/Ji1qe019AtxomotjRVnyc/ALY1ZbkuPP70CliCjYi437zJ+nMTlmBbqEEb8M8OP7DZFwNqolC9f+MCyIhlr5ofgwzSGb0HhIdf1ZoNxd/TitNHOpHS9MXUaJsMyc4DsEAvzVpv8EOzQjjisr9tAI6s8jwz1yv/7bU44bHMpV9bhV5IWjdiDs1qJrYYyD+RAOf9A36RcwgpcEyWGKLd8H+1q8axlI1s1WtdcqGS6PhdNvgNpUelIJHd44usCDgUQBDYf6D2aMlVMwiThHOHUzU9jVtiP8NyEMTomQnN3dZ9BzRv15BKZs8wLJfZHaYVTYQqnNZSPWS0zM9T4Ik1TzI5OFcn8dExn7MXF1xULVXDRFiw85tx4OVJGsvQeLyQjTEjFJzMFLG4mr3S9HglXNAeone9G+kwo7oBpWUEj6ucWISUG+iBy/I7ysA/BGdeI3h/Fjdao9nQFpehR08JKppnztlIo06Iseh2MUUPVy0a4Y/0N7CkbVh2FwciDzV4xAk55PGSW6g6I/vBc+iXHiPps93RYeEEMC36Ip9I23b1/j/ckKZXAf9Dn1mwuVHoaRfzD0VDtKdqbJcJNPHZh90Cl+854l+HvOtehZ02CWtZvK6I=
