language: node_js
node_js:
  - '5'
  - '4'
branches:
  only:
    - src
deploy:
  skip_cleanup: true
  provider: script
  script: ./scripts/deploy.sh
  'on':
    branch: src
    node: '5'
env:
  global:
    - secure: >-
        JAvOXyOntpTuRGOobjizgpsNst41ffPA1sRpaNigv6sJq+76uH15dEs13VizG3uJ5E2snAxLHQDLnHHbopbj9gmEhz8c05ivsiwr9ATW1Iwca4O6znMk02VQj3e6Ej2libcTMENLyhK3ugKg0SFf/dPuxDhrSQ6aYE8D/q//ZbvaNzqtXufrTvKWyC3pbCW4iAn78sRZ7Epvk0e8huQNHb6PQPHhiOUCng1elLmXKxHbwlo5GA6AQF7vfa2X/6X5651+JPzApdC8bv2j2lhGBv5Ac2ZzkF1hVGd0S7VimnYGY9SQlAFjHNqwfepStfntUolpTLmkN4URJbMjmBWnYlYlK07MBfQYJilt+QZxI1EZqO/rcsHkNCmI8HSc3Htrz6kb3mkLAo1ab78gMdPYUIAJEnvuJbn4YG5sGhpJ9lECglqr9hBB07xxAZzIKWRGeCXyhGnjGCBebZBchQym7U9sya3G4t2j7gn1jXqU1+NCq0fmgVu7/EpcfjjLUuuYC4YinWbE/exiYp7Swro6VnYEZMdUwB12nliI1Id6bTNXhE+wvA7uSvHx7kJpKAakFqumOkpKMXj+cE8IQIQAaq4YKmoE+94zBkBlplriTbLfOUm9kF6toeKwOjhRVfukKPtuy7H88odPvNdB7GIv9EnduCaLqYYxRyFGfcK9UKk=

    - GIT_DEPLOY_REPO=https://$GITHUB_TOKEN@github.com/nordsoftware/nordsoftware.github.io.git
